### ISSUE TITLE
Need a JavaFX Repo to Work on

### ISSUE THREAD

**Issue by HEZR0N** [HEZR0N/developers-hand#1]
# Summary

Need a JavaFX repo for my team to pull and begin developing.

## CoS

1. There is a repo with a JavaFX project in it.
1. Everyone on my team can pull the repo onto their local machine
1. Everyone on my team can run the slightly modded JavaFX project

    - [x] Jack
    - [x] Yigit
    - [x] bag
    - [ ] Val22

**Comment by Jack-Huerta11** [comment]
@HEZR0N everything here looks great!

**Comment by The-Yigit** [comment]
@HEZR0N I pulled into my device too.!

**Comment by bagoferasers** [comment]
I was able to download it and open/run it in eclipse just fine but not with VsCode.  Idk how to use eclipse with git yet.

**Comment by Valenciana22** [comment]
Done!
