### ISSUE TITLE
Create Deck Class

### ISSUE THREAD

**Issue by Valenciana22** [HEZR0N/developers-hand#14]
-The "Story" part of the card will take up a lot of space for each card
-Create a Deck Interface with a arraylist of cards field (include getter and setter)
-Create 3 classes that extend the Deck class (ActionDeck, UpgradeDeck, and ObjectiveDeck), each with a loadCards method **declaration** (but **no initialization** because you can't write the initialization without the different card classes already created)
-Create a Data folder under the src folder
-Create three empty csv files for actionDeck, upgradeDeck, and objectiveDeck

**Comment by HEZR0N** [comment]
## Approved
All CoS have been satisfied. Merging
