### ISSUE TITLE
Define UML Diagram

### ISSUE THREAD

**Issue by HEZR0N** [HEZR0N/developers-hand#2]
# Summary

We need to define how the app is structured in order to build it. The UML diagram may be modified as determine new requirements later on.

## CoS

- [ ] All App components are shown in diagram
- [ ] Violet file exists in project folder
- [ ] All SOLID principles are followed:
   - [ ] Single Responsibility: An object should only be modified by it's own methods
   - [ ] Open Closed: No long if/elses. Pass abstract object. Define difference in subclasses.
   - [ ] Liskov Substitution: A child can do everything the parent can do
   - [ ] Interface Segregation: A class must use all methods from the interface it implements
   - [ ] Dependency Inversion: Cards should not depend on players

**Comment by HEZR0N** [comment]
### App Structure Draft
class CARD
   - String Description
   - int XP
   - boolean isBug
   - String color  
   - boolean drawCard
class Bug extends CARD
class Skill extends CARD
class Reputation extends CARD
class Player
  - arraylist of cards
  - int XP
  - int Bugs
 class Game
  - Player arraylist
  - Stats

**Comment by Jack-Huerta11** [comment]
![developers hand UML draft class violet](https://user-images.githubusercontent.com/100225776/160161313-b0852348-3b02-4dc7-9861-443ca5838abd.jpg)

**Comment by Jack-Huerta11** [comment]
i got a basic UML started i was going to wait till i could see everyone's .Java files so that i can put absolutely everything in them

**Comment by Jack-Huerta11** [comment]
![DevHandUML](https://user-images.githubusercontent.com/100225776/164517203-88c74800-699f-4812-a40f-045827dfaa06.png)

**Comment by Jack-Huerta11** [comment]
I updated the UML and made it match the way Rathore would like it
