### ISSUE TITLE
Button Animation

### ISSUE THREAD

**Issue by bagoferasers** [HEZR0N/developers-hand#24]
- # Summary

This should animate buttons a little and add some front-end/css to game.

## CoS

- [ ] animate buttons
- [ ] front-end css
- [ ] anything you can think of?

**Comment by bagoferasers** [comment]
Updated buttons on main menu to include hover, and fixed a mismatch of fonts.

**Comment by bagoferasers** [comment]
Began editing the main game screen.

**Comment by HEZR0N** [comment]
## Feedback 2
By changing fxids to `gameButtonSmall`, you broke code functionality
- [ ] Change any `gameButtonSmall` fxids back to what they were
- [ ] Just list the fxids with commas in the css file

Moving to **Developing** @bagoferasers

**Comment by bagoferasers** [comment]
completed
