### ISSUE TITLE
class Card [Basic]

### ISSUE THREAD

**Issue by HEZR0N** [HEZR0N/developers-hand#5]
# Summary

We need a card class to define the basics:  

- [ ] String Description/story
- [ ] Image picture
- [ ] String event

## CoS

- [ ] There is Card.java file
- [ ] Image picture
- [ ] getters and setters

**Comment by bagoferasers** [comment]
If there are any more things I should add let me know and I'll throw it in.

**Comment by HEZR0N** [comment]
## Feedback
You should add color because all cards will need a color.
Also, event was a poor name choice on my part, since it can be confused with actual program event. Rename `event` to `story` and all associated methods, please.

There was also a problem with the `.classpath` file that wouldn't allow the correct libraries to load in. Here is what the `.classpath` file should contain, according to the sample JavaFX projects provided by the professor, which work (you can copy and paste):
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="con" path="org.eclipse.fx.ide.jdt.core.JAVAFX_CONTAINER"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

Moving to **Developing** @bagoferasers

**Comment by bagoferasers** [comment]
Attempted to fix issues noted in feedback :)

**Comment by HEZR0N** [comment]
@bagoferasers card constructor should use all variables please.

**Comment by bagoferasers** [comment]
@HEZR0N  updated constructor to include all variables.

**Comment by HEZR0N** [comment]
## Approved
All CoS have been satisfied. Moving to **Ready to Merge** @bagoferasers
