### ISSUE TITLE
Game Logo

### ISSUE THREAD

**Issue by HEZR0N** [HEZR0N/developers-hand#7]
# Summary

Need a Game Logo

## CoS

- [ ] Game Logo is Simple 
- [ ] Game Logo is Unique
- [ ] Game Logo appears in top left corner of the app window

**Comment by HEZR0N** [comment]
Logo progression: 
![image](https://user-images.githubusercontent.com/99786488/157103795-95e21375-f6dc-49aa-b04d-2cc7e630634c.png)

**Comment by bagoferasers** [comment]
Approved all CoS has been met @HEZR0N
